---
- name: Create Ubuntu EC2
  hosts: local
  gather_facts: false
  vars:
    ubuntu_owner: "099720109477"   # Canonical
    ubuntu_name_filter: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
  tasks:
    - name: Include AMI discovery (if needed)
      include_role:
        name: ec2
        tasks_from: ami.yml

    - name: Ensure key pair exists (optional create)
      include_role:
        name: ec2
        tasks_from: keypair.yml

    - name: Ensure security group exists (optional create)
      include_role:
        name: ec2
        tasks_from: security_group.yml

    - name: Create instance
      include_role:
        name: ec2
        tasks_from: create.yml

    - name: Output instance details
      debug:
        msg:
          instance_id: "{{ ec2_instance.instance_ids[0] }}"
          public_ip: "{{ ec2_instance.instances[0].public_ip_address | default('') }}"
          private_ip: "{{ ec2_instance.instances[0].private_ip_address }}"
          state: "{{ ec2_instance.instances[0].state.name }}"
