---
- name: Terminate the demo instance
  hosts: local
  gather_facts: false
  vars:
    # Uses the Name tag to find the instance
    instance_name: "{{ instance_name | default('ansible-ubuntu-demo') }}"
    aws_region: "{{ aws_region | default('ap-southeast-1') }}"
  tasks:
    - name: Find instances by Name tag
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: found

    - name: Terminate instances (if any)
      when: found.instances | length > 0
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids: "{{ found.instances | map(attribute='instance_id') | list }}"
        state: terminated
        wait: true

    - name: Report
      debug:
        msg: >-
          {{ (found.instances | length > 0)
              | ternary('Terminated ' ~ (found.instances | length) ~ ' instance(s).',
                        'No instances found with Name=' ~ instance_name) }}
