---
# Entry point. Run infra first, then bootstrap.
- name: Create/Update EC2 infra for Ansible dev
  hosts: local
  gather_facts: false
  roles:
    - role: ec2
      tags: [ec2]

- name: Bootstrap Ansible toolchain on the new server
  hosts: ansible_dev_host
  gather_facts: false
  roles:
    - role: bootstrap
      tags: [bootstrap]
